# Generated by Django 4.0.3 on 2022-05-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(blank=True, max_length=400, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, max_length=400, null=True)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
